routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::resources([
    'employees' => 'EmployeeController',
    'companies' => 'CompanyController'
]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email','phone','company_id'
    ];
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;
use App\Mail\NewUserNotificatio;
use Illuminate\Support\Facades\Mail;
use Illuminate\Http\Request;
use App\Employee;
use App\Company;
use Validator;
class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::all();
        $data = [
            'employees' => $employees
        ];
        return view('employee/content',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();
        $data = [
            'companies' => $companies
        ];
        return view('employee/add',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required|email',
            'phone' => 'required',
            'company_id' => 'required',
        ];
        $customMessages = [
            'required' => 'The :attribute field is mandatory.'
        ];
        $validator = Validator::make($request->all(), $rules, $customMessages);
        if ($validator->fails()) {
            $errors = $validator->errors()->all();
            return view('employees/add')->withErrors($errors);
        }
        $input = $request->all();
        $employee = Employee::create($input);
        if($employee->id){
            Mail::to($input['email'])->send(new NewUserNotificatio);
            return redirect()->route('employees.index');
        }else{
            dd('Failed to add');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::find($id);
        $data = [
            'employee' => $employee
        ];
        return view('employee/edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $employee = Employee::find($id);
        $employee->first_name = $request->first_name;
        $employee->last_name = $request->last_name;
        $employee->email = $request->email;
        $employee->phone = $request->phone;
        $save = $employee->save();
        if($save)
            return redirect()->route('employees.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $del = Employee::destroy($id);
        return redirect()->route('employees.index');
    }
}

resources/views/employee/add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Adding Employee
                    </div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif
                            @if ( $errors->count() > 0 )
                                <p>The following errors have occurred:</p>

                                <ul>
                                    @foreach( $errors->all() as $message )
                                        <li>{{ $message }}</li>
                                    @endforeach
                                </ul>
                            @endif
                            <form class="form-horizontal" action="{{url('/employees')}}" method="post" enctype="multipart/form-data">
                                <fieldset>
                                    {{csrf_field()}}
                                    <!-- Text input-->
                                    <div class="form-group">
                                        <label class="col-md-4 control-label" for="textinput">First Name</label>
                                        <div class="col-md-4">
                                            <input id="textinput" name="first_name" type="text" placeholder="" class="form-control input-md" required="">

                                        </div>
                                    </div>

                                        <!-- Text input-->
                                        <div class="form-group">
                                            <label class="col-md-4 control-label" for="textinput">Last Name</label>
                                            <div class="col-md-4">
                                                <input id="textinput" name="last_name" type="text" placeholder="" class="form-control input-md" required="">

                                            </div>
                                        </div>

                                    <!-- Text input-->
                                    <div class="form-group">
                                        <label class="col-md-4 control-label" for="email">Email</label>
                                        <div class="col-md-4">
                                            <input id="email" name="email" type="text" placeholder="" class="form-control input-md" required="">

                                        </div>
                                    </div>
                                        <!-- Text input-->
                                        <div class="form-group">
                                            <label class="col-md-4 control-label" for="email">Phone</label>
                                            <div class="col-md-4">
                                                <input id="email" name="phone" type="number" placeholder="" class="form-control input-md" required="">

                                            </div>
                                        </div>

                                    <!-- Text input-->
                                    <div class="form-group">
                                        <label class="col-md-4 control-label" for="website">Company ID</label>
                                        <div class="col-md-4">
                                            <select class="form-control" name="company_id">
                                                @if(count($companies))
                                                    @foreach($companies as $company)
                                                    <option value="{{$company->id}}">{{$company->id}}</option>
                                                    @endforeach
                                                    @endif
                                            </select>
                                        </div>
                                    </div>

                                    <!-- Text input-->
                                    <div class="form-group">
                                        <div class="col-md-4">
                                        </div>
                                        <div class="col-md-4">
                                            <input type="submit" class="form-control btn btn-success" value="Submit">
                                        </div>
                                    </div>

                                </fieldset>
                            </form>


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/employee/content.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Employee Listing
                        <span class="pull-right">
                        <a href="{{url('/employees/create')}}"> <button class="btn btn-success">Add</button></a>
                    </span>
                    </div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">First Name</th>
                                    <th scope="col">Last Name</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Phone</th>
                                    <th scope="col">Company ID</th>
                                    <th scope="col">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(count($employees))
                                    @foreach($employees as $employee)
                                        <tr>
                                            <th scope="row">{{$employee->id}}</th>
                                            <td>{{$employee->first_name}}</td>
                                            <td>{{$employee->last_name}}</td>
                                            <td>{{$employee->email}}</td>
                                            <td>{{$employee->phone}}</td>
                                            <td>{{$employee->company_id}}</td>
                                            <td>
                                                <a href="{{url('/employees/'.$employee->id.'/edit')}}"><input type="button" class="btn btn-primary" value="Edit"></a>
                                                <form action="{{ route('employees.destroy', $employee->id) }}" method="POST">
                                                    {{ method_field('DELETE') }}
                                                    {{ csrf_field() }}
                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                </form>


                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td colspan="5">There is no record</td>
                                    </tr>
                                @endif
                                </tbody>
                            </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Editing Employee
                    </div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif
                        @if ( $errors->count() > 0 )
                            <p>The following errors have occurred:</p>

                            <ul>
                                @foreach( $errors->all() as $message )
                                    <li>{{ $message }}</li>
                                @endforeach
                            </ul>
                        @endif
                        <form class="form-horizontal" action="{{url('/employees/'.$employee->id)}}" method="post" enctype="multipart/form-data">
                            <fieldset>
                            {{ method_field('PUT') }}
                            {{csrf_field()}}
                            <!-- Text input-->
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="textinput">First Name</label>
                                    <div class="col-md-4">
                                        <input id="textinput" value="{{$employee->first_name}}" name="first_name" type="text" placeholder="" class="form-control input-md" required="">

                                    </div>
                                </div>
                                <!-- Text input-->
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="textinput">Last Name</label>
                                    <div class="col-md-4">
                                        <input id="textinput" value="{{$employee->last_name}}" name="last_name" type="text" placeholder="" class="form-control input-md" required="">

                                    </div>
                                </div>

                                <!-- Text input-->
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="email">Email</label>
                                    <div class="col-md-4">
                                        <input id="email" name="email" value="{{$employee->email}}" type="text" placeholder="" class="form-control input-md" required="">

                                    </div>
                                </div>

                                <!-- Text input-->
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="website">Phone</label>
                                    <div class="col-md-4">
                                        <input id="phone" name="phone" value="{{$employee->phone}}" type="text" placeholder="" class="form-control input-md" required="">
                                    </div>
                                </div>

                                <!-- Text input-->
                                <div class="form-group">
                                    <div class="col-md-4">
                                    </div>
                                    <div class="col-md-4">
                                        <input type="submit" class="form-control btn btn-success" value="Submit">
                                    </div>
                                </div>

                            </fieldset>
                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection